### ISSUE TITLE
[It broke]: Tranga got hung up after encountering a chapter in an unexpected format

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#78] opened 2023-10-31 21:20 UTC
### What is broken?

After trying to download Given from Manganato, Tranga got hung up on Chapter 39.9 which caused no more jobs to progress and Tranga to restart in the logs multiple times every time it hit this chapter.

### Log-output

```C#
[10/31/2023 21:11:54.826]     Manganato | Getting new Chapters for Publication Given Z2l2ZW4yMDE5

[10/31/2023 21:11:54.826]     Manganato | Getting chapters Publication Given Z2l2ZW4yMDE5

[10/31/2023 21:11:54.826] HttpDownloadC | Waiting 0.7008371 seconds

[10/31/2023 21:11:55.872]     Manganato | Got 68 chapters. Publication Given Z2l2ZW4yMDE5

[10/31/2023 21:11:55.872]     Manganato | Checking for duplicates Publication Given Z2l2ZW4yMDE5

[10/31/2023 21:11:55.872]     Manganato | 66 new chapters. Publication Given Z2l2ZW4yMDE5

Unhandled exception. System.FormatException: The input string 'Special.39.9 : Movie Dvd Bonus' was not in a correct format.

   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)

   at Tranga.MangaConnectors.MangaConnector.<>c.<GetNewChapters>b__12_1(Chapter chapter) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 66

   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)

   at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)

   at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 65

   at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal() in /src/Tranga/Jobs/DownloadNewChapters.cs:line 36

   at Tranga.Jobs.Job.ExecuteReturnSubTasks() in /src/Tranga/Jobs/Job.cs:line 87

   at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 256

   at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74
```

**Comment by C9Glax** [comment] 2023-11-01 13:00
Okay I changed to parsing the chapternumber from the url for this connector as well...

**Comment by darR3Ke** [comment] 2023-11-10 18:10
Had the same happen for Kingdom and Tensei 


`2023-11-09 20:13:00 tranga-api      | [11/09/2023 19:13:00.181]     Manganato | Getting new Chapters for Publication Tensei Shitara Slime Datta Ken dGVuc2Vpc2hpdGFyYXNsaW1lZGF0dGFrZW4yMDE5
2023-11-09 20:13:00 tranga-api      | [11/09/2023 19:13:00.181]     Manganato | Getting chapters Publication Tensei Shitara Slime Datta Ken dGVuc2Vpc2hpdGFyYXNsaW1lZGF0dGFrZW4yMDE5
2023-11-09 20:13:00 tranga-api      | [11/09/2023 19:13:00.334]     Manganato | Got 150 chapters. Publication Tensei Shitara Slime Datta Ken dGVuc2Vpc2hpdGFyYXNsaW1lZGF0dGFrZW4yMDE5
2023-11-09 20:13:00 tranga-api      | [11/09/2023 19:13:00.334]     Manganato | Checking for duplicates Publication Tensei Shitara Slime Datta Ken dGVuc2Vpc2hpdGFyYXNsaW1lZGF0dGFrZW4yMDE5
2023-11-09 20:13:00 tranga-api      | [11/09/2023 19:13:00.481]     Manganato | 134 new chapters. Publication Tensei Shitara Slime Datta Ken dGVuc2Vpc2hpdGFyYXNsaW1lZGF0dGFrZW4yMDE5
2023-11-09 20:13:00 tranga-api      | Unhandled exception. System.FormatException: The input string 'Vol.1 Bonus Short Story: Veldora's Slime Observation Journal' was not in a correct format.
2023-11-09 20:13:00 tranga-api      |    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
2023-11-09 20:13:00 tranga-api      |    at Tranga.MangaConnectors.MangaConnector.<>c.<GetNewChapters>b__12_1(Chapter chapter) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 66
2023-11-09 20:13:00 tranga-api      |    at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
2023-11-09 20:13:00 tranga-api      |    at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
2023-11-09 20:13:00 tranga-api      |    at Tranga.MangaConnectors.MangaConnector.GetNewChapters(Manga manga, String language) in /src/Tranga/MangaConnectors/MangaConnector.cs:line 65
2023-11-09 20:13:00 tranga-api      |    at Tranga.Jobs.DownloadNewChapters.ExecuteReturnSubTasksInternal() in /src/Tranga/Jobs/DownloadNewChapters.cs:line 36
2023-11-09 20:13:00 tranga-api      |    at Tranga.Jobs.Job.ExecuteReturnSubTasks() in /src/Tranga/Jobs/Job.cs:line 87
2023-11-09 20:13:00 tranga-api      |    at Tranga.Jobs.JobBoss.CheckJobs() in /src/Tranga/Jobs/JobBoss.cs:line 256
2023-11-09 20:13:00 tranga-api      |    at Tranga.Tranga.<StartJobBoss>b__10_0() in /src/Tranga/Tranga.cs:line 74`

**Comment by arxae** [comment] 2023-11-12 04:50
If i try to reproduce it, i don't get any error at all. Has the docker image been updated yet?

**Comment by C9Glax** [comment] 2023-11-12 11:50
@arxae @darR3Ke 
The problem is fixed on `cuttingedge` branch, just not yet merged into `latest` https://github.com/C9Glax/tranga/commit/8f5dd5aab58bb95579432e1978dbe8a8c176ea53

**Closed by C9Glax** 2023-11-12 11:50 UTC
Labels: bug
