### ISSUE TITLE
CPU Usage in Unraid

### ISSUE THREAD

**Issue by lsultana98** [C9Glax/tranga#20] opened 2023-06-13 04:09 UTC
Bulk downloading of Manga causes a gradual uptick in CPU usage until it gets to a pretty high level. Not too sure why. As soon as I drop the container, the CPU returns to its usual idle of around 20%. 

If I start the container back up, it will be fine for ten minutes. Then go up 10% load, etc etc until it is around 85% consistently.

For reference, the idle of around 20% is with around 20 containers (including book/manga/video/audio servers/downloaders/monitoring services), and 2x Windows 10 VMs. I have a scheduled task to restart the container in the interim, hence why it isn't urgent.

**Comment by C9Glax** [comment] 2023-06-13 14:59
Hey there, I haven't been able to observe this behaviour, and since the only CPU-"intensive" task is zipping files, I suppose that wouldn't be the cause.

Can you provide logs from the point +++++++where the load is at max? 
I suppose you know how but just in case: `docker compose logs`.

**Comment by lsultana98** [comment] 2023-06-14 01:03
Hopefully this isn't annoying. Just to show the fluctuation of CPU usage over time + the logs under the peak. I have it all in a pdf. 

[Tranga CPU Usage.pdf](https://github.com/C9Glax/tranga/files/11740466/Tranga.CPU.Usage.pdf)

**Comment by C9Glax** [comment] 2023-06-14 14:11
I appreciate the extensiveness. You can also just copy paste logs as code here.
Since you are using Mangasee and I haven't yet I suspect it is that connector in connection with the headless browser running in the background. I will do some testing to see if that might be the case.
Thanks for now :)

**Comment by lsultana98** [comment] 2023-06-14 21:13
Thanks mate, look forward to hearing back.

**Comment by C9Glax** [comment] 2023-06-15 17:11
Hey there, sadly I haven't been able to reproduce your behaviour...
GarbageCollection is doing it's thing and properly deleting all instances, and even after 20 Minutes my RAM and CPU usage were below 1%.
I will keep the issue open, if anybody else experiences the same behaviour, please provide logs and your setup information.

**Comment by lsultana98** [comment] 2023-06-16 00:14
This is so odd. I don't know if you noticed, but I reported a docker image filling up issue on your reddit post from last week. And it randomly fixed it self with a new update for your package. And the exact same thing just happened with this CPU issue. It isn't happening today. Feel free to close if you'd like.

**Comment by lsultana98** [comment] 2023-06-16 01:48
I'm confused by this one. I cant figure out why -.-

**Comment by C9Glax** [comment] 2023-06-16 16:56
Me too, since the only CPU-intensive task would be rendering webpages, but those should be disposed of (as I can also confirm by looking at memory usage), and otherwise I really have no clues.
Shot in the dark:
How are IO-Operations looking? Is there a way to check?

**Comment by lsultana98** [comment] 2023-06-18 23:48
iops don't look too bad, it is a little hard to tell for sure sometimes due to all the other functions running on the server

**Comment by JohnnyBigoud** [comment] 2023-08-31 08:22
I host tranga in docker container - through docker compose - and my server gets overloaded as well. I singled out Tranga as responsible since when I stop this container after hard reboot it doesn't occur anymore.

- I didn't check logs or anything more yet
- Symptoms were that all my hosted services on this headless server were very slow / unresponsive.
- I was in the process of mass bulk imports to initialize my library from scratch.

I'll try to provide input as much as possible if you can point me towards which files to provide.

**Comment by C9Glax** [comment] 2023-08-31 18:05
Hey there! First off thanks for confirming that this is not a single occurence.
However at the moment I am in the process of rewriting large parts of the project #41 , so I won't work on this for now, in case it might get resolved.
However I suspect, that GarbageCollection is having trouble somewhere releasing some of my objects (because I don't have very much experience in writing multi-threaded applications), and after a while those will clog up the system.
I can recommend two options:

1. Restart your container on a frequent basis
2. limit cpu and memory usage through the docker compose, that way at least your other services wont throttle.

**Comment by JohnnyBigoud** [comment] 2023-08-31 18:52
Thanks a lot for the reply. No worries, I just wanted to contribute not throwing any stones here. Your time spent on this project is very appreciated.

**Comment by C9Glax** [comment] 2023-08-31 19:46
No offence taken. I appreciate all the encouraging words 👍🏼

**Comment by C9Glax** [comment] 2023-09-02 20:53
I might have identified an issue:
Have any of you used Mangasee as Connector?

**Comment by JohnnyBigoud** [comment] 2023-09-05 08:43
Hello,
Yes I have used it for some manga references. Is it a an issue linked to this connector only?

**Comment by C9Glax** [comment] 2023-09-05 17:30
Yes indeed, Mangasee is (so far) the only connector that requires a headless browser (to execute javascript).
All other connectors serve either static websites, or have a full-blown API.

However atm Tranga isn't closing open webpages (therefor GC can't free the memory).
This would explain why usage is extremely high especially on first-setup.
I just pushed a small commit that should close webpages after requests, could you report back any changes?

**Comment by JohnnyBigoud** [comment] 2023-09-06 07:26
Container updated and running. I’ll update later after some runtime.

**Comment by JohnnyBigoud** [comment] 2023-09-07 13:34
After 1 day of uptime I don't see any performances issues anymore. I'll continue monitoring

**Comment by C9Glax** [comment] 2023-09-07 13:37
Would be great if this gets resolved.
@lsultana98 if you are still running Tranga can you report wether your system-load has improved with the latest version?

**Closed** 2023-09-19 15:06 UTC
Labels: bug, help wanted

**Comment by derp90** [comment] 2023-11-13 17:55
I am having very high CPU usage and am using mangasee as the connector

**Comment by derp90** [comment] 2023-11-14 05:03
I removed all mangasee connected managa's and CPU usage dropped to the ground.
