### ISSUE TITLE
[It broke]: Manganato duplicate manga

### ISSUE THREAD

**Issue by ghost** [C9Glax/tranga#232] opened 2024-08-27 14:15 UTC
### What is broken?

I have Charlotte from Manganato, when trying to add https://manganato.com/manga-du980803 it doesnt show that its downloading anything and the card for Fate/grand Order -Turas Réalta- is also not there. 
But instead a duplicate card of Charlotte appears, in my files there is only one Charlotte and Fate/grand Order -Turas Réalta-
![image](https://github.com/user-attachments/assets/279261ce-b4d6-45a8-99a2-5463c6d5d7d5)
![image](https://github.com/user-attachments/assets/d82c1d8b-d708-40d8-a549-388ed394e3e2)

The logs also talk about adding Charlotte, which makes 0 sense sincei added Turas Realta..

### Log-output

```C#
tranga-api  | [08/27/2024 14:11:48.594]       JobBoss | Adding Job to Queue. Tranga.Jobs.DownloadNewChapters-Y2hhcmxvdHRlMjAyNA== Manga: Publication Charlotte Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:48.596]     Manganato | Getting new Chapters for Publication Charlotte Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:48.597]     Manganato | Getting chapters Publication Charlotte Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:48.887]     Manganato | Got 35 chapters. Publication Charlotte Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:48.891]     Manganato | Checking for duplicates Publication Charlotte Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:48.903]     Manganato | 0 new chapters. Publication Charlotte Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:48.905]     Manganato | Copy cover Publication Charlotte Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:48.905]     Manganato | Cover exists Publication Charlotte Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:48.906]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.DownloadNewChapters-Y2hhcmxvdHRlMjAyNA==.json
tranga-api  | [08/27/2024 14:11:48.921]       JobBoss | Added Tranga.Jobs.UpdateMetadata-Y2hhcmxvdHRlMjAyNA== Manga: Publication Charlotte Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:48.921]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.UpdateMetadata-Y2hhcmxvdHRlMjAyNA==.json
tranga-api  | [08/27/2024 14:11:48.924]       JobBoss | Adding Job to Queue. Tranga.Jobs.UpdateMetadata-Y2hhcmxvdHRlMjAyNA== Manga: Publication Charlotte Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:49.26 ]       JobBoss | Next job in -00:00:00.0000002 Tranga.Jobs.UpdateMetadata-Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:49.232]     Manganato | Overwriting Manga Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:49.232]       JobBoss | Exporting Job /usr/share/tranga-api/jobs/Tranga.Jobs.UpdateMetadata-Y2hhcmxvdHRlMjAyNA==.json
tranga-api  | [08/27/2024 14:11:49.334]       JobBoss | Removing Tranga.Jobs.UpdateMetadata-Y2hhcmxvdHRlMjAyNA== Manga: Publication Charlotte Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:49.334] UpdateMetadat | Cancelling Tranga.Jobs.UpdateMetadata-Y2hhcmxvdHRlMjAyNA== Manga: Publication Charlotte Y2hhcmxvdHRlMjAyNA==
tranga-api  | [08/27/2024 14:11:49.335]       JobBoss | Deleting Job-file /usr/share/tranga-api/jobs/Tranga.Jobs.UpdateMetadata-Y2hhcmxvdHRlMjAyNA==.json
tranga-api  | [08/27/2024 14:11:49.335]       JobBoss | Next job in 00:26:07.7533195 Tranga.Jobs.DownloadNewChapters-Ym9jY2hpdGhlcm9jazIwMTg=
```

**Comment by ElryMoe** [comment] 2024-08-27 14:21
The other fate stuff is working just fine aswell, its just that one fate manga that tranga things is a duplicate of Charlotte for some reason, it seems to download and track it correctly, so its not the end of the world, still weird tho

**Comment by ElryMoe** [comment] 2024-08-27 14:24
![image](https://github.com/user-attachments/assets/97c018a9-7e6e-4c55-8fd5-402347fb4cb5)
It doesnt seem to download the manga acutally, so it creates a duplicate of charlotte, which i know dont know which is the real one, but it also doesnt even download the actual manga that i wanted Fategrand Order -Turas Réalta-

**Comment by ElryMoe** [comment] 2024-08-27 14:34
Trying to add the same manga from MangaDex or MangaKatana results in the same, a duplicate Charlotte.
Only MangaHere worked, but that one also only downloaded an empty folder.

**Comment by Nas-77** [comment] 2024-08-30 02:28
Also experiencing duplicate manga issue as well as previously deleted monitor job keeps coming back. But for me it is when my tranga docker container restarts. Experiencing it with both Mangadex and Mangakatana sources.   

Noticed that when I look at the tranga > settings > jobs, instead of removing a DownloadNewChapter file after removing the problematic manga, it would just add an additional DownloadNewChapter file.

**Comment by Nas-77** [comment] 2024-08-30 06:04
Did a clean install of Tranga and reimported all the monitor jobs, seemed to have fixed the issue for me.

**Comment by C9Glax** [comment] 2024-09-09 08:03
Got a fix on main machine, forgot to push, next week 👍🏼

**Closed** 2024-09-16 19:12 UTC
Labels: bug

**Comment by C9Glax** [comment] 2024-09-16 19:14
Fixed in `cuttingedge`
