### ISSUE TITLE
Add PUID and GUID variables to Docker container

### ISSUE THREAD

**Issue by yacob841** [C9Glax/tranga#127] opened 2024-02-14 13:28 UTC
I currently have been using let’s say 104:105 as my PUID and GUID for Kaizoku and Komga. Tranga 90% of the time is using root:root, not sure why/how but there has been 2 times where it’s set it to 104:105. (This has been causing my Komga to not be able to view any books downloaded by Tranga) I've tried using the "user" field in docker-compose but that causes issues with internal permission denied errors

**Comment by C9Glax** [comment] 2024-02-14 17:01
Duplicate of #100 
You are creating the container as root which is why all files are created with that user.
The current workaround is to create the container as 104:105 .

**Closed by C9Glax** 2024-02-14 17:01 UTC
